# Generated by Django 5.1.4 on 2025-01-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_useraccount_groups_useraccount_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('planner', 'Planner')], default='viewer', max_length=50),
        ),
    ]
